added db creation for tests

diff --git a/.github/workflows/elixir.yml b/.github/workflows/elixir.yml
--- a/.github/workflows/elixir.yml
+++ b/.github/workflows/elixir.yml
@@ -4,18 +4,32 @@ on: push
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     container:
       image: elixir:1.9.1-slim
 
     steps:
-    - uses: actions/checkout@v1
-    - name: Install Dependencies
-      run: |
-        mix local.rebar --force
-        mix local.hex --force
-        mix deps.get
-    - name: Run Tests
-      run: mix test
+      - uses: actions/checkout@v1
+      - name: Install Dependencies
+        run: |
+          mix local.rebar --force
+          mix local.hex --force
+          mix deps.get
+    - name: Create DB
+        run: |
+          sudo apt-get update
+          sudo apt-get install postgresql-client -y
+          ATTEMPTS=10
+          until PGPASSWORD=password psql -h 127.0.0.1 -U postgres -d postgres -c "select 1" > /dev/null 2>&1; do
+            if [ $ATTEMPTS -eq 0 ]; then
+              echo "Unable to connect to postgres!!"
+              exit 1
+            fi
+            echo "Waiting for postgres server, $((ATTEMPTS--)) remaining attempts..."
+            sleep 1
+          done
+      - name: Create Schema
+        run: mix ecto.create --quiet
+      - name: Run Tests
+        run: mix test
